default_context:
  category: general
  description: Recursively zip up a directory/folder
  git_base_url: https://github.com
  git_group: jmknoble
  git_project: zipdir
  git_url: https://github.com/jmknoble/zipdir
  package_name: zipdir
  project_name: zipdir
  project_type: python
  team_email: jmknoble@pobox.com
  team_name: Jim Knoble
  title: zipdir
  version: 0.3.5
